name: CI
on: 
    push:
        branches:
            - master
        pull_request:
jobs:
    build-test:
        runs-on: ubuntu-latest
        steps:
        - name: Running tests
          uses: php-actions/composer@v5
          with:
              php_version: 7.3
              version: 2
              command: composer run test
