on: 
    pull_request:
        branches:
            - master

name: CI

jobs:
    build-test:
        name: Running tests
        runs-on: ubuntu-latest
        steps:
          uses: php-actions/composer@v5
          with:
              php_version: 7.3
              version: 2
              command: composer run test
